spring:
  application:
    title: Indicadores
    name: Indicadores
  neo4j:
    uri: bolt://localhost:7687
    authentication:
        username: neo4j
        password: Indicadores@

application:
    name: Indicadores
    version: 1.0.0

frontend:
  host: http://localhost:4200

server:
  hostname:
  port: 8080
  servlet:
    context-path: /indicadores-api