spring:
  application:
    name: Indicadores
  profiles:
    active: dev
  # autenticacao acesso cidadao
  security:
    oauth2:
      client:
        provider:
          acessocidadao:.issuer-uri: 
        registration:
          acessocidadao.client-name: 
          acessocidadao.client-id: 
          acessocidadao.client-secret: 
          acessocidadao.authorization-grant-type: 
          acessocidadao.redirect-uri: 
          acessocidadao.scope: 
  
  neo4j:
    uri: bolt://localhost:7687/neo4j
    authentication:
        username: neo4j
        password: Indicadores@

application:
    name: Indicadores
    version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /indicadores-api


# JWT
token:
  secret: 

# Hostname do frontend da aplicacao
frontend:
  host: http://localhost:4200